# Restart kitty:
# kitty @ load-config

term xterm-256color
allow_remote_control yes

#include ./kitty-themes/themes/Apprentice.conf
#include ./my.theme.conf

copy_on_select yes
select_by_word_characters @-./_~?&%+#

cursor_shape block
cursor_shape_unfocused hollow
shell_integration no-cursor

enable_audio_bell no


font_size 13.0
font_family MesloLGS Nerd Font Mono

background_opacity 0.8

background_blur 32

tab_bar_style powerline

window_padding_width 8

hide_window_decorations titlebar-only
cursor_blink_interval 0

map cmd+backspace send_text all \x15
# it seems not needed anymore as: "macos_option_as_alt yes"
map option+backspace send_text all \x17
macos_option_as_alt yes
inherit_env yes

## scrolback limit
scrollback_lines -1

## Layouts
enabled_layouts splits

map f5 launch --location=hsplit --cwd=current
map f6 launch --location=vsplit --cwd=current
map cmd+t new_tab_with_cwd
map cmd+n new_os_window_with_cwd

# Move the active window in the indicated direction
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down
# Move the active window to the indicated screen edge
map ctrl+shift+up layout_action move_to_screen_edge top
map ctrl+shift+left layout_action move_to_screen_edge left
map ctrl+shift+right layout_action move_to_screen_edge right
map ctrl+shift+down layout_action move_to_screen_edge bottom
# Switch focus to the neighboring window in the indicated direction
map cmd+left neighboring_window left
map cmd+right neighboring_window right
map cmd+up neighboring_window up
map cmd+down neighboring_window down

# attach/deattach tabs(windows)
map f1 detach_tab ask

## Theme
# https://github.com/dexpota/kitty-themes
cursor     #5fd787
# directory
color4     #7199bc
# git
color2  #95a863

# cursor     #c7c7c7
# cursor_text_color #feffff
# selection_foreground #3e3e3e
# selection_background #c1ddff
# foreground #c8c8c8
# background #323232
# color0     #252525
# color8     #555555
# color1     #be7472
# color9     #ff9900
# color2     #709772
# color10    #97bb98
# color3     #989772
# color11    #fefdbc
# color4     #7199bc
# color12    #9fbdde
# color5     #727399
# color13    #989abc
# color6     #719899
# color14    #6fbbbc
# color7     #7f7f7f
# color15    #feffff
